# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5c66c3b16b24fd13b4bcee79321a5b0609fac492858e1d05abefb568df58f2c01c51a13685c3e8e15cd29a8662aa4b16588866c89c4f127468b4a23e9427ec03

test:
  secret_key_base: 7bbe8b8a63873f6353ac94261aa9d55db38c5f75ee759bf1430c2609fe8aa10f8b790493a82ce892021728df8dc122c778a665f0b3ea6e5361620a1ba55635a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
